### ISSUE TITLE
Separating Concerns

### ISSUE THREAD

**Issue by jsteyn** [NewcastleRSE/WorkshopScheduler_Java#1]
- [x] Restructure src use Model/View/Controller
- [x] Split HTML into HTML and CSS files

**Comment by jsteyn** [comment]
- Restructure src to MVC
- Split HTML into HTML and CSS files

**Comment by NeatuR** [comment]
I have addressed CSS into its own file with a class for testing. This sits in the folder that created HTML sits in. 
Commit can be found [here](https://github.com/NewcastleRSE/WorkshopScheduler_Java/commit/61d573b48fc0f7e77789639358a7fba51248c32d)
