### ISSUE TITLE
Allow user to re-order episodes

### ISSUE THREAD

**Issue by jsteyn** [NewcastleRSE/WorkshopScheduler_Java#3]
- [x] Style the GUI table
- [x] After reading episode for a specific lesson from a CSV file, display the episodes in a tables.
- [x] Allow the user to re-order the episodes
- [x] Allow the user to add new episodes
- [x] Allow the user to delete episodes
- [x] If the episodes are viewed in the context of a lesson, calculate the start time of each episode based on the start time of the lesson

**Comment by NeatuR** [comment]
-the start time is calculated in the HTML, but not in the table
-the CSV is displayed as a CSV with the option to be opened as a table
