### ISSUE TITLE
Create a basic JFrame GUI for the application

### ISSUE THREAD

**Issue by jsteyn** [NewcastleRSE/WorkshopScheduler_Java#6]
- [x] Create a JFrame with a JPanel and a JTextArea
- [x] Create JLabel and JTextFields for start hour etc.
- [x] Create a JMenuBar with
- [x] File
  - Open
  - Save
  - Create HTML

Open should use JFileChooser to open a CSV file and load it into the TextArea where it can be edited and then saved with the Save menu option. 

Using the 'Create HTML' menu item the file should then be exported to a file called schedule.html with the HTML version of the schedule.

**Comment by NeatuR** [comment]
@jsteyn I didn't put the buttons "Upload(Open) CSV", "Save CSV", "Create HTML" into a JMenubar but I could. Do you think is necessary? Please see the last commit.  Maybe the JMenuBar could have other options?
