### ISSUE TITLE
Given the start time of the project, use the episode duration to calculate the start time for each episode.

### ISSUE THREAD

**Issue by jsteyn** [NewcastleRSE/WorkshopScheduler_Java#7]

**Comment by NeatuR** [comment]
I believe this is already done - commit [here](https://github.com/NewcastleRSE/WorkshopScheduler_Java/commit/b1c8c34447cbc9a641bebf8852a6cba7d6b01fb5)
 Is this what you mean?

**Comment by jsteyn** [comment]
Yes, I think that's it. I just wanted it added to the list of issues so that we know it is covered. I'll close this issue now.
